//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiDichVuChoThueXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LOAIXE
    {
        public string MaLoai { get; set; }
        public string HangXe { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual tbl_BANGLAI tbl_BANGLAI { get; set; }
    }
}
