//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiDichVuChoThueXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PHIEUTHUE
    {
        public string MaPhieu { get; set; }
        public string SoXe { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public Nullable<int> SoNgayMuon { get; set; }
    
        public virtual tbl_KHACHHANG tbl_KHACHHANG { get; set; }
        public virtual tbl_THONGTINXE tbl_THONGTINXE { get; set; }
    }
}
